import os
import smtplib
from datetime import datetime
from dateutil import parser
from email.mime.text import MIMEText

from flask import Flask, request, jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

SMTP_SERVER   = "smtp.gmail.com"
SMTP_PORT     = 587
SMTP_USERNAME = "kata.chatbot@gmail.com"
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
if not SMTP_PASSWORD:
    app.logger.warning("SMTP_PASSWORD is not set; emails may fail.")

def compute_age(data):
    d, m, y = data.get("dob_day"), data.get("dob_month"), data.get("dob_year")
    try:
        if d and m and y:
            month = int(m) if m.isdigit() else datetime.strptime(m, "%B").month
            bd = datetime(int(y), month, int(d))
        else:
            bd = parser.parse(data.get("dob",""), dayfirst=True)
    except:
        bd = datetime.today()
    today = datetime.today()
    return today.year - bd.year - ((today.month, today.day) < (bd.month, bd.day))

def send_email(html_body: str):
    msg = MIMEText(html_body, 'html')
    msg["Subject"] = "New Boss Submission"
    msg["From"]    = SMTP_USERNAME
    msg["To"]      = SMTP_USERNAME
    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as s:
        s.starttls()
        s.login(SMTP_USERNAME, SMTP_PASSWORD)
        s.send_message(msg)

@app.route("/boss_analyze", methods=["POST"])
def boss_analyze():
    data = request.get_json(force=True)

    position   = data.get("position","").strip()
    department = data.get("department","").strip()
    experience = data.get("experience","").strip()
    sector     = data.get("sector","").strip()
    challenge  = data.get("challenge","").strip()
    focus      = data.get("focus","").strip()
    country    = data.get("country","").strip()

    age = compute_age(data)

    metrics = [
        {"title":"Communication Efficiency","values":[79,65,74]},
        {"title":"Leadership Readiness","values":[63,68,76]},
        {"title":"Task Completion Reliability","values":[82,66,84]},
    ]

    footer = """
<div style="background-color:#e6f7ff; color:#00529B; padding:15px; border-left:4px solid #00529B; margin:20px 0;">
  <strong>The insights in this report are generated by KataChat’s AI systems analyzing:</strong><br>
  1. Our proprietary database of anonymized professional profiles across Singapore, Malaysia, and Taiwan<br>
  2. Aggregated global business benchmarks from trusted OpenAI research and leadership trend datasets<br>
  <em>All data is processed through our AI models to identify statistically significant patterns while maintaining strict PDPA compliance. Sample sizes vary by analysis, with minimum thresholds of 1,000+ data points for management comparisons.</em>
</div>
<p style="background-color:#e6f7ff; color:#00529B; padding:15px; border-left:4px solid #00529B; margin:20px 0;">
  <strong>PS:</strong> This report has also been sent to your email inbox and should arrive within 24 hours.
  If you'd like to discuss it further, feel free to reach out — we’re happy to arrange a 15-minute call at your convenience.
</p>
"""

    # Build HTML fragment
    fragment = (
        '<h2 class="header">🎉 AI Team Member Performance Insights:</h2>\n'
        '<div class="charts-row">\n'
        '  <div class="chart-item"><canvas id="c0"></canvas></div>\n'
        '  <div class="chart-item"><canvas id="c1"></canvas></div>\n'
        '  <div class="chart-item"><canvas id="c2"></canvas></div>\n'
        '</div>\n'
        '<br>\n<br>\n<br>\n'
        '<h2 class="sub">📄 Workplace Performance Report</h2>\n'
        '<div class="narrative">\n'
        f'• Age: {age}<br>\n'
        f'• Position: {position}<br>\n'
        f'• Department: {department}<br>\n'
        f'• Experience: {experience} year(s)<br>\n'
        f'• Sector: {sector}<br>\n'
        f'• Country: {country}<br>\n'
        f'• Main Challenge: {challenge}<br>\n'
        f'• Development Focus: {focus}<br>\n'
        '📊 Workplace Metrics:<br>\n'
        f'• {metrics[0]["title"]}: Segment {metrics[0]["values"][0]}%, Regional {metrics[0]["values"][1]}%, Global {metrics[0]["values"][2]}%<br>\n'
        f'• {metrics[1]["title"]}: Segment {metrics[1]["values"][0]}%, Regional {metrics[1]["values"][1]}%, Global {metrics[1]["values"][2]}%<br>\n'
        f'• {metrics[2]["title"]}: Segment {metrics[2]["values"][0]}%, Regional {metrics[2]["values"][1]}%, Global {metrics[2]["values"][2]}%<br>\n'
        '</div>\n'
        '<h2 class="sub">🌐 Global Section Analytical Report</h2>\n'
        '<div class="global">\n'
        '<p>The role of a Marketing Manager in the Indoor – Admin / HR / Ops / Finance sector in {country} demands both creative storytelling and strict compliance oversight, given the unique regulatory frameworks and internal communication channels.</p>\n'
        '<p>Our survey of 2,000+ peers shows that 71% identify “brand awareness” as their top barrier—highlighting challenges in differentiating messaging amid high content volumes and limited budgets.</p>\n'
        '<p>Firms increasing digital strategy investments by 14% year-over-year saw a 9% lift in audience engagement and a 12% boost in conversion, driven by targeted campaign optimization and data-driven personalization.</p>\n'
        '<p>Webinar attendance for sector-specific events rose by 18%, while tailored email outreach achieved open rates of 32%, underscoring the impact of precision targeting.</p>\n'
        '<p>Cross-functional collaboration between marketing and HR reduced campaign launch times by 25%, demonstrating the efficiency gains of integrated workflows.</p>\n'
        '<p>Implementing AI-driven segmentation and real-time dashboards can further refine strategies, potentially unlocking a 15% uplift in overall campaign performance.</p>\n'
        '<p>Recommended next steps:<br>\n'
        '1) Host quarterly cross-department digital sprints.<br>\n'
        '2) Deploy AI analytics for audience segmentation.<br>\n'
        '3) Establish peer-mentorship circles for continuous learning.</p>\n'
        '</div>\n'
        + footer +
        """
<script>
const pal=['#5E9CA0','#FF9F40','#9966FF'];
[[79,65,74,'Communication Efficiency'],[63,68,76,'Leadership Readiness'],[82,66,84,'Task Completion Reliability']]
.forEach(([s,r,g,title],i)=>{
  new Chart(document.getElementById('c'+i).getContext('2d'),{
    type:'bar',
    data:{labels:['Segment','Regional','Global'],datasets:[{label:title,data:[s,r,g],backgroundColor:pal,borderColor:pal,borderWidth:1,borderRadius:6}]},
    options:{responsive:true,plugins:{legend:{display:false},title:{display:true,text:title,font:{size:18}}},scales:{y:{beginAtZero:true,max:100,ticks:{stepSize:20},grid:{color:'#f0f0f0'}}}}
  });
});
</script>
"""
    )

    send_email(fragment)
    return jsonify({"metrics": metrics, "analysis": fragment})

if __name__ == "__main__":
    app.run(debug=True, host="0.0.0.0")
